server:
  port: 1234
# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/demo?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
      username: root
      password: junmp123
      driver-class-name: com.mysql.cj.jdbc.Driver
